spring:
  application:
    name: glancy
  datasource:
    url: jdbc:mysql://localhost:3306/glancy_db?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: glancy_user
    password: your_password_here
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true