spring:
    application:
        name: glancy
    messages:
        basename: messages
    mail:
        host: localhost
        port: 1025
    datasource:
        url: jdbc:mysql://localhost:3306/glancy_db?useSSL=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
        username: glancy_user
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                format_sql: true

management:
    endpoints:
        web:
            exposure:
                include: health,info

logging:
    level:
        com.glancy.backend: DEBUG

search:
    limit:
        nonMember: 10

thirdparty:
    deepseek:
        base-url: https://api.deepseek.com
        api-key: ''

portal:
    admin-token: secret
    qianwen:
        base-url: https://api.qianwen.com
