name: Restart Backend

on:
    workflow_dispatch:

jobs:
    restart:
        runs-on: ubuntu-latest
        steps:
            - name: Restart backend service
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SERVER_KEY }}
                  script: |
                      sudo systemctl restart glancy-backend.service

