name: Restart Backend

on:
    workflow_dispatch:

jobs:
    restart:
        runs-on: ubuntu-latest
        steps:
            - name: Restart backend service
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SERVER_KEY }}
                  script: |
                      if sudo systemctl list-units --type=service --all | grep -q 'glancy-backend.service'; then
                          sudo systemctl restart glancy-backend.service
                      else
                          echo 'glancy-backend.service not found on remote host'
                      fi

